<?xml version="1.0"?>
<!-- rover -->
<robot name="rover" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>

  <!-- define colors -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>

  <!-- base dimensions -->
  <xacro:property name="base_x_size" value="0.6" />
  <xacro:property name="base_y_size" value="0.4" />
  <xacro:property name="base_z_size" value="0.2" />

  <!-- wheel properties -->
  <xacro:property name="wheel_length" value="0.1" />
  <xacro:property name="wheel_radius" value="0.15" />

  <!-- base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia
        ixx="0.133" ixy="0.0" ixz="0.0"
        iyy="0.133" iyz="0.0"
        izz="0.133"/>
    </inertial>
  </link>

  <!-- wheels -->
  <link name="left_front_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.0133" ixy="0.0" ixz="0.0"
        iyy="0.0133" iyz="0.0"
        izz="0.0133"/>
    </inertial>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_front_wheel_link"/>
    <origin xyz="${(base_x_size/2)} ${(base_y_size/2 + wheel_length)} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.01"/>
  </joint>

  <link name="right_front_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.0133" ixy="0.0" ixz="0.0"
        iyy="0.0133" iyz="0.0"
        izz="0.0133"/>
    </inertial>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_front_wheel_link"/>
    <origin xyz="${(base_x_size/2)} ${-1*(base_y_size/2 + wheel_length)} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.01"/>
  </joint>

  <link name="left_rear_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.0133" ixy="0.0" ixz="0.0"
        iyy="0.0133" iyz="0.0"
        izz="0.0133"/>
    </inertial>
  </link>

  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel_link"/>
    <origin xyz="${-1*(base_x_size/2)} ${(base_y_size/2 + wheel_length)} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.01"/>
  </joint>

  <link name="right_rear_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia
        ixx="0.0133" ixy="0.0" ixz="0.0"
        iyy="0.0133" iyz="0.0"
        izz="0.0133"/>
    </inertial>
  </link>

  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel_link"/>
    <origin xyz="${-1*(base_x_size/2)} ${-1*(base_y_size/2 + wheel_length)} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.01"/>
  </joint>

  <!-- plugins -->
  <gazebo>
    <plugin filename="libignition-gazebo-joint-state-publisher-system.so"
            name="ignition::gazebo::systems::JointStatePublisher"/>
  </gazebo>

</robot>